const MODULES = [
  {
    id: "home",
    icon: "⚡",
    label: "Mission Control",
    title: "GitSimulator — Free Interactive Git & GitHub Course | Learn Git Online",
    description: "Free interactive Git and GitHub course with 24 hands-on modules. Practice git commands in a live terminal, visualize branches, resolve merge conflicts, and master GitHub workflows. No sign-up required.",
    keywords: "git tutorial, github tutorial, learn git, learn github, git course, github course, git for beginners, git commands, interactive git simulator, git tutorial for beginners, github simulator, git online, git training, learn git online free, git cheat sheet, git branching tutorial, github workflow, version control tutorial, git and github tutorial, how to use git, how to use github",
  },
  {
    id: "init",
    icon: "🌱",
    label: "git init",
    title: "git init Tutorial — How to Initialize a Git Repository | GitSimulator",
    description: "Learn how to use git init to create a repository from scratch. Explore .git internals, bare repos, templates, and git clone with an interactive hands-on simulator.",
    keywords: "git init, initialize git repository, git init tutorial, how to create a git repo, git internals, git basics, git init command, create new git repository, git init example, what does git init do",
  },
  {
    id: "staging",
    icon: "📦",
    label: "Stage & Commit",
    title: "git add & git commit Tutorial — Staging Area Explained | GitSimulator",
    description: "Master the Git staging area with git add and git commit. Learn to stage files, write good commit messages, amend commits, and undo changes with interactive practice.",
    keywords: "git add, git commit, git staging area, how to commit in git, git commit tutorial, stage files git, git add command, git commit message, how to use git add, git commit example, undo git commit, git amend commit",
  },
  {
    id: "branch",
    icon: "🌿",
    label: "Branching",
    title: "Git Branch Tutorial — Create, Switch & Delete Branches | GitSimulator",
    description: "Learn Git branching: create branches, switch with git checkout or git switch, list and delete branches. Practice with an interactive branch simulator.",
    keywords: "git branch, git branching tutorial, create branch git, git checkout, git switch, delete branch git, git branch command, how to create a branch in git, git branch example, git new branch, git list branches, git branching strategy",
  },
  {
    id: "merge",
    icon: "🔀",
    label: "Merge & Rebase",
    title: "Git Merge & Rebase Tutorial — Resolve Conflicts Step by Step | GitSimulator",
    description: "Master git merge and git rebase. Learn merge strategies, resolve merge conflicts step by step, understand fast-forward vs 3-way merge, and interactive rebase.",
    keywords: "git merge, git rebase, merge conflict, resolve git conflict, git merge tutorial, fast-forward merge, 3-way merge, git merge command, how to resolve merge conflicts in git, git rebase tutorial, git merge vs rebase, git conflict resolution",
  },
  {
    id: "remote",
    icon: "☁",
    label: "Remote & Push",
    title: "Git Remote, Push & Pull Tutorial — Sync with GitHub | GitSimulator",
    description: "Learn git remote, git push, git pull, and git fetch. Understand how to sync local repos with GitHub, set upstream branches, manage origins, and collaborate remotely.",
    keywords: "git remote, git push, git pull, git fetch, github remote repository, git origin, upstream branch, git push command, how to push to github, git pull command, git remote add origin, git clone, how to sync git with github",
  },
  {
    id: "pullrequest",
    icon: "🤝",
    label: "Pull Requests",
    title: "GitHub Pull Request Tutorial — Create, Review & Merge PRs | GitSimulator",
    description: "Learn how to create, review, and merge GitHub Pull Requests. Understand the PR lifecycle, code review best practices, draft PRs, and branch merging strategies.",
    keywords: "github pull request, how to create pull request, PR tutorial, github code review, open pull request, merge pull request, pull request github, github PR, what is a pull request, pull request vs merge request, github pull request tutorial, create PR github",
  },
  {
    id: "gitflow",
    icon: "🔄",
    label: "Git Flow",
    title: "Git Flow Tutorial — Branching Strategy for Teams | GitSimulator",
    description: "Learn the Git Flow branching strategy with feature branches, release branches, hotfixes, and a develop/main workflow. Interactive Git Flow simulator.",
    keywords: "git flow, git branching strategy, git flow tutorial, feature branch workflow, release branch, hotfix branch",
  },
  {
    id: "advanced",
    icon: "⚗",
    label: "Advanced Magic",
    title: "Advanced Git Commands — Stash, Cherry-pick, Bisect & Reflog | GitSimulator",
    description: "Master advanced Git commands: git stash, cherry-pick, bisect, reflog, reset, revert, and interactive rebase. Level up your Git workflow with hands-on practice.",
    keywords: "advanced git commands, git stash, git cherry-pick, git bisect, git reflog, git reset, interactive rebase, git revert, git stash tutorial, how to use git stash, git cherry-pick example, git reset hard, git undo changes, advanced git tutorial",
  },
  {
    id: "worktree",
    icon: "🌲",
    label: "Git Worktree",
    title: "Git Worktree Tutorial — Work on Multiple Branches Simultaneously | GitSimulator",
    description: "Learn git worktree to check out multiple branches at once in separate directories. Manage parallel workstreams, hotfixes, and code reviews without stashing or switching branches.",
    keywords: "git worktree, git worktree tutorial, git worktree add, git multiple branches, git worktree example, work on two branches at once, git worktree vs git stash, git worktree remove, git worktree list, git parallel development, git worktree command, how to use git worktree",
  },
  {
    id: "collaborate",
    icon: "🌐",
    label: "Open Source",
    title: "Open Source Contribution Guide — Fork, Clone & PR | GitSimulator",
    description: "Learn to contribute to open source on GitHub. Fork repos, clone, create branches, submit pull requests, and work as a collaborator on real projects.",
    keywords: "open source contribution, github fork, how to contribute to open source, github collaboration, fork and clone, open source beginner",
  },
  {
    id: "visualizer",
    icon: "📊",
    label: "Commit Graph",
    title: "Git Commit Graph Visualizer — Visual Branch History | GitSimulator",
    description: "Visualize Git commit history, branches, and merges with an interactive commit graph. Understand Git topology and branch history visually.",
    keywords: "git commit graph, git visualizer, git history visualization, git branch diagram, git log graph, commit history",
  },
  {
    id: "actions",
    icon: "🤖",
    label: "GitHub Actions",
    title: "GitHub Actions Tutorial — CI/CD Workflow Automation Guide | GitSimulator",
    description: "Learn GitHub Actions to automate CI/CD pipelines, run tests, build and deploy apps with YAML workflow files. Step-by-step examples for every use case.",
    keywords: "github actions, github actions tutorial, CI/CD github, github workflow yaml, github automation, continuous integration, github actions example, github actions deploy, github CI CD tutorial, github actions workflow, how to use github actions, github actions for beginners",
  },
  {
    id: "security",
    icon: "🔐",
    label: "Security",
    title: "GitHub Security — Secret Scanning, Dependabot & Code Scanning",
    description: "Learn GitHub security features: secret scanning, code scanning, Dependabot alerts, security advisories, and best practices for securing your repository.",
    keywords: "github security, github secret scanning, code scanning github, github security features, dependabot security, repository security",
  },
  {
    id: "issues",
    icon: "🐛",
    label: "Issues",
    title: "GitHub Issues Tutorial — Bug Tracking & Feature Requests",
    description: "Learn how to use GitHub Issues for bug tracking and feature requests. Covers labels, milestones, assignees, issue templates, and project integration.",
    keywords: "github issues, github bug tracker, github issue tutorial, github issue templates, github labels, github milestones",
  },
  {
    id: "projects",
    icon: "📋",
    label: "GitHub Projects",
    title: "GitHub Projects Tutorial — Kanban & Project Management",
    description: "Learn GitHub Projects for agile project management. Create Kanban boards, track sprints, manage workflows, and organize issues with custom views.",
    keywords: "github projects, github kanban board, github project management, github project tutorial, github roadmap, github backlog",
  },
  {
    id: "pages",
    icon: "🌍",
    label: "GitHub Pages",
    title: "GitHub Pages Tutorial — Deploy Static Websites for Free",
    description: "Learn how to deploy static websites with GitHub Pages. Set up custom domains, use Jekyll, configure auto-deploy from branches, and host docs for free.",
    keywords: "github pages, github pages tutorial, deploy with github pages, github pages custom domain, host website github, free static hosting",
  },
  {
    id: "releases",
    icon: "📦",
    label: "Releases",
    title: "GitHub Releases Tutorial — Tag & Publish Versions | GitSimulator",
    description: "Learn to create GitHub Releases, tag versions with semantic versioning, write changelogs, attach binary assets, and automate releases with Actions.",
    keywords: "github releases, github release tutorial, git tags, semantic versioning, publish github release, release changelog",
  },
  {
    id: "protection",
    icon: "🔒",
    label: "Branch Protection",
    title: "GitHub Branch Protection Rules — Enforce Code Quality",
    description: "Learn GitHub branch protection rules: require code reviews, status checks, signed commits, and prevent force pushes to protect your main branch.",
    keywords: "github branch protection, branch protection rules, require pull request review, github protected branches, enforce workflows",
  },
  {
    id: "codeowners",
    icon: "👑",
    label: "CODEOWNERS",
    title: "GitHub CODEOWNERS Tutorial — Auto-Assign PR Reviewers | GitSimulator",
    description: "Learn the GitHub CODEOWNERS file to automatically assign reviewers for pull requests. Define ownership patterns for files, directories, and teams.",
    keywords: "codeowners file, github codeowners tutorial, CODEOWNERS, auto assign reviewers github, github code ownership, required reviewers",
  },
  {
    id: "githubapi",
    icon: "🔌",
    label: "GitHub API",
    title: "GitHub REST API Tutorial — Automate GitHub with the API",
    description: "Learn the GitHub REST and GraphQL APIs. Authenticate with tokens, manage repos, issues, and PRs programmatically. Includes Octokit and webhook examples.",
    keywords: "github api, github rest api, github api tutorial, github graphql api, github octokit, github webhooks, automate github",
  },
  {
    id: "dotgithub",
    icon: "📂",
    label: ".github Folder",
    title: ".github Folder Guide — Templates & Workflows | GitSimulator",
    description: "Learn the .github folder: issue templates, PR templates, GitHub Actions workflows, CODEOWNERS, FUNDING.yml, and community health files.",
    keywords: ".github folder, github templates, github issue template, github pr template, github community health, FUNDING.yml",
  },
  {
    id: "dependabot",
    icon: "🤖",
    label: "Dependabot",
    title: "Dependabot Tutorial — Automate Dependency Updates | GitSimulator",
    description: "Learn GitHub Dependabot to automatically update dependencies, receive security vulnerability alerts, and auto-create pull requests for package updates.",
    keywords: "dependabot, github dependabot tutorial, automate dependency updates, dependabot.yml, github security alerts, npm security updates",
  },
  {
    id: "codespaces",
    icon: "💻",
    label: "Codespaces",
    title: "GitHub Codespaces Tutorial — Cloud Dev Environment | GitSimulator",
    description: "Learn GitHub Codespaces to create instant cloud-based development environments. Configure devcontainers, manage ports, and use prebuilds for faster startup.",
    keywords: "github codespaces, codespaces tutorial, cloud development environment, devcontainer, github dev, browser IDE, cloud coding",
  },
  {
    id: "quiz",
    icon: "🧠",
    label: "Master Quiz",
    title: "Git & GitHub Quiz — Test Your Knowledge Free | GitSimulator",
    description: "Test your Git and GitHub knowledge with a free interactive quiz covering branching, pull requests, GitHub Actions, commits, merge conflicts, and advanced Git concepts.",
    keywords: "git quiz, github quiz, git knowledge test, learn git quiz, github certification practice, git exam, github exam, git interview questions, github interview questions, git test, version control quiz",
  },
];

export default MODULES;
