const MODULES = [
  { id: "home",        icon: "⚡", label: "Mission Control", title: "GitSimulator — Master GitHub", description: "Interactive Git and GitHub learning app. Master git init, branching, merging, pull requests, and more through hands-on simulators." },
  { id: "init",        icon: "🌱", label: "git init", title: "git init — GitSimulator", description: "Learn how to initialize repositories, create commits, and start using Git locally." },
  { id: "staging",     icon: "📦", label: "Stage & Commit", title: "Stage & Commit — GitSimulator", description: "Practice staging files and creating commits; learn how the index and working tree interact." },
  { id: "branch",      icon: "🌿", label: "Branching", title: "Branching — GitSimulator", description: "Create and manage branches to isolate work, experiment, and merge safely." },
  { id: "merge",       icon: "🔀", label: "Merge & Rebase", title: "Merge & Rebase — GitSimulator", description: "Understand merges, rebases, and conflict resolution with hands-on examples." },
  { id: "remote",      icon: "☁",  label: "Remote & Push", title: "Remote & Push — GitSimulator", description: "Learn how to connect remotes, push and fetch changes, and collaborate via origin." },
  { id: "pullrequest", icon: "🤝", label: "Pull Requests", title: "Pull Requests — GitSimulator", description: "Simulate creating pull requests, reviews, and merging contributions on GitHub." },
  { id: "gitflow",     icon: "🔄", label: "Git Flow", title: "Git Flow — GitSimulator", description: "Explore branching strategies like Git Flow and how to structure releases and hotfixes." },
  { id: "advanced",    icon: "⚗",  label: "Advanced Magic", title: "Advanced Git — GitSimulator", description: "Deep-dive into advanced git topics: reflog, bisect, submodules, and low-level plumbing." },
  { id: "collaborate", icon: "🌐", label: "Open Source", title: "Open Source Collaboration — GitSimulator", description: "Best practices for contributing to open-source projects and managing community workflows." },
  { id: "visualizer",  icon: "📊", label: "Commit Graph", title: "Commit Graph — GitSimulator", description: "Visualize commit history, branches, and merges to understand repository state." },
  { id: "actions",     icon: "🤖", label: "GitHub Actions", title: "GitHub Actions — GitSimulator", description: "Learn CI/CD basics: workflows, actions, and automating checks for your projects." },
  { id: "security",    icon: "🔐", label: "Security", title: "Security — GitSimulator", description: "Understand security practices: secrets, dependabot, code scanning, and protected branches." },
  { id: "issues",      icon: "🐛", label: "Issues", title: "Issues & Triage — GitSimulator", description: "Manage issues, labels, and triage strategies to keep projects organized." },
  { id: "projects",    icon: "📋", label: "GitHub Projects", title: "Projects — GitSimulator", description: "Track work with GitHub Projects (boards, tables) and organize team priorities." },
  { id: "pages",       icon: "🌍", label: "GitHub Pages", title: "GitHub Pages — GitSimulator", description: "Host static sites from repos using GitHub Pages and custom domains." },
  { id: "releases",    icon: "📦", label: "Releases", title: "Releases — GitSimulator", description: "Learn semantic versioning and how to publish releases and changelogs." },
  { id: "protection",  icon: "🔒", label: "Branch Protection", title: "Branch Protection — GitSimulator", description: "Configure required reviews, status checks, and rules to protect important branches." },
  { id: "codeowners",  icon: "👑", label: "CODEOWNERS", title: "CODEOWNERS — GitSimulator", description: "Use CODEOWNERS to assign reviewers automatically and establish ownership." },
  { id: "githubapi",   icon: "🔌", label: "GitHub API", title: "GitHub API — GitSimulator", description: "Explore the GitHub REST API and authenticate requests to automate workflows." },
  { id: "dotgithub",   icon: "📂", label: ".github Folder", title: ".github Configuration — GitSimulator", description: "Configure community files, actions, and issue templates using the .github folder." },
  { id: "dependabot",  icon: "🤖", label: "Dependabot", title: "Dependabot — GitSimulator", description: "Automate dependency updates and security fixes with Dependabot configuration." },
  { id: "codespaces",  icon: "💻", label: "Codespaces", title: "Codespaces — GitSimulator", description: "Set up reproducible dev environments with GitHub Codespaces and devcontainers." },
  { id: "quiz",        icon: "🧠", label: "Master Quiz", title: "Master Quiz — GitSimulator", description: "Test your Git knowledge with short quizzes that reinforce key concepts." },
];

export default MODULES;
